test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,12 +1,24 @@
 #!/usr/bin/env bash
 
+# Fail fast and fail hard.
+set -eo pipefail
+
+# Paths.
+BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
 BUILD_DIR=$1
 CACHE_DIR=$2
 
-set -e
+unset GIT_DIR
 
-indent() {
-  sed -u 's/^/       /'
+# We'll need to send these statics to other scripts we `source`.
+export BUILD_DIR CACHE_DIR BIN_DIR
+
+function indent() {
+  c='s/^/ /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *) sed -u "$c";;
+  esac
 }
 
 function build() {
@@ -48,9 +60,13 @@ function build() {
   fi
 }
 
+source $BIN_DIR/hooks/pre_compile
+
 for buildpack in $(cat $BUILD_DIR/.buildpacks); do
   build $buildpack
 done
+
+source $BIN_DIR/hooks/post_compile
 
 
 echo "Using release configuration from last framework $framework:" | indent
